version: "1.0"
stages:
  - "clone"
  - "build"
  - "integration"
  - "push"
steps:
  clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "animeshon/comingsoon"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "animeshon/comingsoon"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
  parallel_push:
    type: "parallel"
    stage: "push"
    steps:
      annotate_build:
        title: "Annotating Build"
        image: "${{build}}"
        working_directory: "IMAGE_WORK_DIR"
        commands:
          - "echo Annotating Build..."
        on_success:
          metadata:
            set:
              - ${{build.imageId}}:
                  - CF_QUALITY: true
        on_error:
          metadata:
            set:
              - ${{build.imageId}}:
                  - CF_QUALITY: false
      push_cfcr:
        title: "Pushing image to Codefresh Container Registry"
        type: "push"
        image_name: "comingsoon"
        registry: "cfcr"
        candidate: "${{build}}"
        tags:
          - "${{CF_BRANCH_TAG_NORMALIZED}}"
          - "${{CF_REVISION}}"
      push_gcr:
        title: "Pushing image to Google Cloud Registry"
        type: "push"
        image_name: "comingsoon"
        registry: "gcr-tier-0"
        candidate: "${{build}}"
        tags:
          - "${{CF_BRANCH_TAG_NORMALIZED}}"
          - "${{CF_REVISION}}"
  plan:
    stage: "plan"
    setup_terraform:
      image: alpine:3.9
      title: Setting up Terraform CLI configuration file
      stage: prepare
      commands:
        - ./terraform/setup.sh
    terraform_plan:
      image: hashicorp/terraform:0.12.0
      title: Generation Terraform execution plan
      stage: plan
      commands:
        - terraform init
        - terraform plan
  approval_for_deploy:
    stage: "deploy"
    type: "pending-approval"
    title: "Waiting for deployment approval"
  deploy:
    stage: "deploy"
    execute_terraform:
      image: hashicorp/terraform:0.12.0
      title: Executing Terraform plan
      stage: deploy
      commands:
        - terraform init
        - terraform apply -auto-approve 